//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PubEntAdmin.UserControl {
    
    
    public partial class ROOTabEditInfo {
        
        /// <summary>
        /// lblDisStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblDisStatus;
        
        /// <summary>
        /// ckboxListDisplayStatusROO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PubEntAdmin.CustomControl.CkboxListDisplayStatus ckboxListDisplayStatusROO;
        
        /// <summary>
        /// lblMaxQty control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMaxQty;
        
        /// <summary>
        /// txtMaxQtyROO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtMaxQtyROO;
        
        /// <summary>
        /// ftxteMaxQtyROO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.FilteredTextBoxExtender ftxteMaxQtyROO;
        
        /// <summary>
        /// lblInclEveryOrder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblInclEveryOrder;
        
        /// <summary>
        /// rdbtnListYesNoEveryOrder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PubEntAdmin.CustomControl.RdbtnListYesNo rdbtnListYesNoEveryOrder;
        
        /// <summary>
        /// lblShowInSrchRes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblShowInSrchRes;
        
        /// <summary>
        /// rdbtnListYesNoShowInSearchRes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PubEntAdmin.CustomControl.RdbtnListYesNo rdbtnListYesNoShowInSearchRes;
        
        /// <summary>
        /// lblROOKit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblROOKit;
        
        /// <summary>
        /// rdbtnListYesNoROOKit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PubEntAdmin.CustomControl.RdbtnListYesNo rdbtnListYesNoROOKit;
        
        /// <summary>
        /// lblSubj control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSubj;
        
        /// <summary>
        /// listSubject control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PubEntAdmin.UserControl.ListMultiSelect listSubject;
        
        /// <summary>
        /// lblCollections control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCollections;
        
        /// <summary>
        /// listCollections control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PubEntAdmin.UserControl.ListMultiSelect listCollections;
    }
}
